### PR TITLE
Iteration 2

### LINKED ISSUE #2: Set up CI
Link repo to Travis CI for testing

### LINKED ISSUE #5: Play button to start game
- [x] Display name of game
- [x] Display button
- [x] On click, button starts game (loads first question)

### LINKED ISSUE #6: Display questions and answers one at a time
- [x] Question displays
- [x] Answers display, both correct & incorrect
- [x] Answers are shuffled so correct is not always in same place
- [x] Questions are shuffled so they are not always in same order

### LINKED ISSUE #7: Check if chosen answer is correct
- [x] On click, answers are compared against correct answer

### LINKED ISSUE #9: Display next question after one has been answered
- [x] On click, "next" button displays the next question and set of answers

### PR DESCRIPTION
**Pull request by lilianaweimer**
## Pull request checklist
Please check if your PR fulfills the following requirements:
- [x] Compiler warnings have been dealt with

## Pull request type
 
 
Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Testing
- [ ] Other (please describe): 

## What is the current behavior?

- The app had no content

## What is the new behavior?

- Added basic display of title, description, and play button in `Home` component
- Added shuffling to make question order random, then also answer order
- Display questions and allow the user to answer them*
- Add two tests to `App`, that took a long time because of a React Hooks warning (`act wrapper` warning)
- Added Travis CI `.yml` file for CI
- Made the data fetching into a mocked API call so changing it over will be easier later

## Does this introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

*Realized I accidentally did most of iteration 3 here, too... whoops! I got carried away. The only thing I'm missing is the score. And a lot of testing. Thus...
closes #5 
closes #6 
closes #7 
closes #9 
closes #2 

### Using Gitmoji from https://gitmoji.carloscuesta.me/

### CODE REVIEW

File: src/Components/App/App.js [hunk 1]
```diff
@@ -1,21 +1,60 @@
 import React, { useEffect, useState } from 'react';
+import { Route, Switch } from 'react-router-dom';
 import './App.scss';
 
-import data from '../../Data/Apprentice_TandemFor400_Data.json';
+import Home from '../Home/Home';
+import Game from '../Game/Game';
+import GameOver from '../GameOver/GameOver';
+
+import { getQuestions } from '../../Data/apiCalls';
```
Comment (lilianaweimer) [inline src/Components/App/App.js:9]: Mocking this seems silly :p but I think it will be a good idea in the long run

File: src/Components/App/App.scss [hunk 2]
```diff
@@ -1,38 +1,38 @@
-.App {
-  text-align: center;
-}
+// .App {
+//   text-align: center;
+// }
```
Comment (lilianaweimer) [inline src/Components/App/App.scss:3]: I will need to work on styling soon. The app doesn't look so hot right now...

File: src/Components/App/App.test.js [hunk 3]
```diff
@@ -1,8 +1,61 @@
...
+
+  it('should render the home component on initial mount', async () => {
+    getQuestions.mockResolvedValueOnce(mockQuestion);
+    await act(async () => {
+      ReactDOM.render(<MemoryRouter><App /></MemoryRouter>, container)
+    });
+
+    expect(container.querySelector('h1').textContent).toBe('Tandem for 400');
+    expect(container.querySelector('p').textContent).toBe('Train your trivia knowledge!');
+    expect(container.querySelector('[data-testid=play-button]').textContent).toBe('Play');
```
Comment (lilianaweimer) [inline src/Components/App/App.test.js:42]: This syntax is super weird to me, but it fixed the `act wrapper` warning. I will need to do more research into this!

File: src/Components/Game/Game.js [hunk 4]
```diff
@@ -0,0 +1,78 @@
+import React, { useState } from 'react';
+import { Redirect } from 'react-router';
+import './Game.scss';
+
+const Game = ({ gameData, shuffle }) => {
+
+  const [currentIndex, incrementQIndex] = useState(0);
+  const [display, changeDisplay] = useState('play');
+  const question = gameData[currentIndex]
```
Comment (lilianaweimer) [inline src/Components/Game/Game.js:9]: Missing a `;` 😱

**Review by lilianaweimer — COMMENTED** [review]
Alright! Progress! The testing was a bit of a nightmare, but I got some tests passing at long last. I will need to write tests for all of this before starting on new functionality tomorrow (although there isn't much left to hit MVP). Things to consider:
- The questions seem to persist on refresh, which is interesting. That could cause some odd behavior with restarting the game
- I need to get the score implemented! But what should it increment by?

**Comment by lilianaweimer** [comment]
Note before I merge:
the Travis build took a LONG time to run for some reason. If that continues to be a problem I might have to switch to using a different CI. I'll just keep an eye on it for now.
